### ISSUE TITLE
TNB Gifts

### ISSUE THREAD

**Issue by picko1990** [thenewboston-developers/Project-Proposals#201]
# Project Details

#### How would you describe your project?
TNB Gifts, will be a cool app that allows users to gift images to their friends from the available collection

#### What problem does this project solve?
It creates more activity on the network

#### Who is the target market?
Everyone who owns a TNBC account

#### How will this project benefit the network and/or the community?
It will generate more activity

#### How is this project centered around thenewboston?
it is all about TNBC, so it is fully centered around thenewboston

#### What is the estimated completion date for this project? (rough estimates are acceptable)
may take from 3 weeks to 2 months

#### Please include a detailed roadmap for your project below. This must include a list of all milestones where payments will be awarded upon completion of each.
ANSWER HERE

#### What is your Discord username?
picko1990#6172

# Milestone Details

#### Milestone Description
First milestone will be a fully functional MVP, that allows sending and viewing messages

#### Requested Payment Upon Completion

| # | Objective           | Estimated Value (coins)   |
| - | ------------------- | ------------------------- |
| 1 | MVP with basic UI | 60,000 |

#### Project Reviewer
Preferred: @itsnikhil 

#### Project Wallet
b0b0b98f9bd0b9809ac30706363ccfe7294fc5dc06eec9fb916bb17e8d91536e

**Comment by manishram** [comment]
@itsnikhil is going to reach @picko1990 regarding some additional info and some concerns regarding this proposal.

**Comment by angle943** [comment]
hello @picko1990 we have reviewed this project, and we like it, but we would want a few clarifications.

- Will milestone 1 contain the UI completed?

If the UI won't be completed for milestone 1, then we (the auditors) will need some form of a way to verify the proof of work. Since the UI won't be ready, you can either record the screen of it working, or you can revise the milestone to include a basic UI that we can test with.

If delivered with screen recording as proof of work, then we will offer 40,000. With a basic UI that we can test with, then we can offer 60,000.

Let us know which direction you want to go with!

**Comment by picko1990** [comment]
Hi @angle943 @manishram milestone 1 will have a basic UI and I have revised the milestone according to that.

**Comment by angle943** [comment]
milestone 1 approved for 60,000 coins!

**Comment by picko1990** [comment]
Thank you!
Here is the project repository: https://github.com/picko1990/tnbgifts
