### ISSUE TITLE
suppCoins - Completed web app (MVP) - 3

### ISSUE THREAD

**Issue by Toledit** [thenewboston-developers/Project-Proposals#317]
#### Link to the milestone and objectives table.
#193 More or less the milestones here are done with.

#### Detailed log of all completed objectives including valid proof of work.
| # | Milestones           | Objectives   |
| - | -------------------- | ------------------------- |
| 1 | Frontend Implementation | Front log-in, Sign-up, reset password, forget password, home page, post detail page, profile page & edit profile, dashboard stat |
| 2 | Backend Implementation | Backend login, registration, profile CRUD (+ follow,unfollow), content CRUD(image,video) like/unlike, supp/comment, Notification & Search engine, dashboard overview |
| 3 | Deployment (Temp Server) | http://suppcoin.herokuapp.com/ (deployed temporarily on a free server)|

The project is deployed on [suppCoins temp server](http://suppcoin.herokuapp.com). Anyone, Feel free to test it out by signing up with a fake email and fake TNB wallet address for now and leave some suggestions here or discord (7oledit#8388).

**Note**: _This is MVP product. So features will definitely get added, might get changed, modified, or removed._
 
#### Project Wallet
449baf4c0b43f44e9b091947bf36880bf237a91e413adb85ca2ae1f33e239440

**Comment by tspearing** [comment]
@Toledit, it looks like it isn't yet possible to complete the transactions. Please add this to complete the MVP.

**Comment by manishram** [comment]
1. The option to edit my own post is not available until I refresh the page after posting.
![image](https://user-images.githubusercontent.com/22790904/155124378-3b6f7ac1-cb09-40ed-a103-5b985940177b.png)

2. The profile section after email verifications keep on loading and nothing happens. I opened a new tab to get into the app.
![image](https://user-images.githubusercontent.com/22790904/155124615-86fc1580-acea-43fb-ac99-b5a91b5c43a7.png)

3. The project team can use the Free version of Zoho Mail to get their professional domain email instead of using Gmail.
https://www.zoho.com/mail/zohomail-pricing.html?src=zmail
![image](https://user-images.githubusercontent.com/22790904/155125065-ca34e31c-50bc-4d2f-bde6-9e1928695475.png)

**Comment by manishram** [comment]
Approved for 750K TNBC
